import assert from 'node:assert/strict';
import { chromium } from '@playwright/test';

// Run with: node github-preview.test.mjs. Standalone concept; no server or provider account.
const browser = await chromium.launch();
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  const network = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => { if (/^https?:/.test(request.url())) network.push(request.url()); });
  await page.goto(new URL('./github-preview.html?lang=en', import.meta.url).href);
  const rows = page.locator('#list article');
  const tab = name => page.getByRole('button', { name, exact: false }).filter({ has: page.locator('.count') });
  const action = number => page.locator(`#list article[data-item$="/${number}"]`).getByRole('button', { name: 'Open workspace', exact: true });
  await page.context().route('https://**/*', route => route.fulfill({ body: '<title>External destination</title>' }));
  async function opensExternal(link, expected, keyboard = false) {
    const opened = page.waitForEvent('popup');
    if (keyboard) { await link.focus(); await page.keyboard.press('Enter'); }
    else await link.click();
    const popup = await opened;
    await popup.waitForLoadState();
    assert.equal(popup.url(), expected);
    await popup.close();
  }
  assert.equal(await page.getByRole('heading', { name: 'Issues', exact: true }).isVisible(), true);
  assert.equal(await page.locator('.sidebar .nav-item').count(), 2, 'One Issues entry must contain both providers.');
  assert.equal(await page.locator('#detail').count(), 0, 'The detail panel must be removed.');
  assert.equal(await rows.count(), 4);
  await opensExternal(page.getByRole('link', { name: 'Restore terminal state when reopening a workspace', exact: true }), 'https://github.com/prometeucorp/prometeu/issues/428');
  await page.getByRole('textbox', { name: 'Search by title' }).fill('#93');
  assert.equal(await rows.count(), 1);
  await action(93).click();
  assert.equal(await page.getByRole('textbox', { name: 'Repository directory', exact: true }).inputValue(), '');
  await page.getByRole('button', { name: 'Create in preview', exact: true }).click();
  assert.equal(await page.getByRole('dialog').isVisible(), true);
  await page.keyboard.press('Escape');
  assert.equal(await action(93).evaluate(node => node === document.activeElement), true);
  await page.getByRole('textbox', { name: 'Search by title' }).fill('nonexistent');
  assert.equal(await rows.count(), 0);
  assert.equal(await page.getByRole('heading', { name: 'No results', exact: true }).isVisible(), true);
  await page.getByRole('button', { name: 'Clear filters', exact: true }).click();
  await page.getByRole('combobox', { name: 'All repositories', exact: true }).selectOption('prometeucorp/prometeu-cloud');
  assert.equal(await rows.count(), 1);
  await tab('From repositories').click();
  assert.equal(await rows.count(), 6);
  await page.getByRole('button', { name: 'Choose repositories' }).click();
  for (const checkbox of await page.getByRole('checkbox').all()) await checkbox.uncheck();
  await page.getByRole('button', { name: 'Save selection', exact: true }).click();
  assert.equal(await page.getByRole('heading', { name: 'Choose what to follow', exact: true }).isVisible(), true);
  await tab('My issues').click();
  assert.equal(await rows.count(), 4, 'Repository selection must not hide assigned issues.');
  await page.locator('#choose-repositories').click();
  await page.getByRole('checkbox', { name: 'acme/design-system', exact: true }).check();
  await page.getByRole('button', { name: 'Save selection', exact: true }).click();
  await tab('From repositories').click();
  assert.equal(await rows.count(), 1);
  await tab('My issues').click();
  await action(428).click();
  assert.match(await page.getByRole('textbox', { name: 'Initial context', exact: true }).inputValue(), /https:\/\/github.com\/prometeucorp\/prometeu\/issues\/428/);
  await page.getByRole('button', { name: 'Create in preview', exact: true }).click();
  assert.equal(await action(428).textContent(), 'Open workspace');
  assert.equal(page.context().pages().length, 1, 'Workspace action must not open the issue URL.');
  const workspaceCount = await page.locator('#workspace-list button').count();
  await action(428).click();
  await page.getByRole('button', { name: 'Back to list', exact: true }).click();
  assert.equal(await page.locator('#workspace-list button').count(), workspaceCount);
  await tab('My PRs').click();
  assert.equal(await rows.count(), 3);
  assert.match((await rows.allTextContents()).join('\n'), /Draft/);
  await tab('To review').click();
  assert.equal(await rows.count(), 2);
  await opensExternal(rows.first().getByRole('link'), 'https://github.com/prometeucorp/prometeu/pull/438');
  await action(438).click();
  assert.equal(await page.getByRole('textbox', { name: 'Branch', exact: true }).inputValue(), 'fix/review-file-renames');
  assert.equal(await page.getByRole('textbox', { name: 'Branch', exact: true }).getAttribute('readonly'), '');
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: 'Linear', exact: true }).click();
  assert.equal(await rows.count(), 3);
  assert.equal(await page.locator('#choose-repositories').isVisible(), false);
  assert.equal(await page.getByRole('combobox', { name: 'All teams', exact: true }).isVisible(), true);
  await opensExternal(page.getByRole('link', { name: 'Keep terminal sessions alive when switching tabs', exact: true }), 'https://linear.app/prometeu/issue/ENG-142', true);
  await action(142).click();
  assert.match(await page.getByRole('textbox', { name: 'Initial context', exact: true }).inputValue(), /https:\/\/linear.app\/prometeu\/issue\/ENG-142/);
  await page.getByRole('button', { name: 'Create in preview', exact: true }).click();
  assert.equal(page.context().pages().length, 1);
  await action(142).click();
  await page.getByRole('button', { name: 'Back to list', exact: true }).click();
  await page.getByRole('combobox', { name: 'All teams', exact: true }).selectOption('Cloud');
  assert.equal(await rows.count(), 1);
  await tab('Available in my teams').click();
  assert.equal(await rows.count(), 2);
  await page.getByRole('button', { name: 'GitHub', exact: true }).click();
  await tab('My issues').click();
  await page.screenshot({ path: '/tmp/prometeu-github-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.screenshot({ path: '/tmp/prometeu-github-mobile.png', fullPage: true });
  assert.deepEqual(errors, []);
  assert.deepEqual(network, [], 'Preview must work offline.');
  console.log('Issues preview: provider tabs, direct external links, separate workspace actions, filters, creation/reuse, review branch, focus, narrow layout, and offline use passed.');
} finally {
  await browser.close();
}
