import {
  invoke as tauriInvoke,
  type InvokeArgs,
  type InvokeOptions,
} from "@tauri-apps/api/core";

/**
 * Commands exposed by the Rust backend and currently consumed by the frontend.
 * Keeping the boundary here makes misspelled or stale command names a type error.
 */
export const IPC_COMMANDS = [
  "add_project",
  "agents",
  "claude_models",
  "archive_workspace",
  "browser_back",
  "browser_bounds",
  "browser_close",
  "browser_forward",
  "browser_hide",
  "browser_navigate",
  "browser_open",
  "browser_reload",
  "browser_url",
  "chat_buffer",
  "chat_control",
  "chat_control_remote",
  "chat_send",
  "chat_snapshot",
  "cleanup_list",
  "file_stamp",
  "cleanup_worktree",
  "close_dock",
  "close_tab",
  "create_scripts_file",
  "create_workspace",
  "dock_state",
  "find_paths",
  "finish_workspace",
  "focus_tab",
  "linear_connect",
  "linear_disconnect",
  "linear_issues",
  "linear_open",
  "linear_status",
  "legacy_import_plan",
  "legacy_import_run",
  "list_branches",
  "list_dir",
  "load_board",
  "look_at",
  "machine",
  "mcp_check",
  "mcp_found",
  "mcp_hub",
  "mcp_login",
  "mcp_logins",
  "mcp_logout",
  "mcp_remove",
  "mcp_save",
  "new_tab",
  "open_dock",
  "open_external",
  "open_pr",
  "open_run",
  "pin_workspace",
  "plugin_hub",
  "plugin_install",
  "plugin_look",
  "plugin_make",
  "plugin_make_stop",
  "plugin_remove",
  "plugin_save",
  "plugin_scrap",
  "plugin_update",
  "pr_open",
  "pr_prompt",
  "pty_buffer",
  "pty_resize",
  "pty_write",
  "read_bytes",
  "read_file",
  "refresh_prs",
  "remove_workspace",
  "rename_tab",
  "rename_workspace",
  "reveal",
  "scripts_prompt",
  "set_awake",
  "set_lang",
  "set_shared",
  "set_stage",
  "set_tab_choice",
  "set_unread",
  "set_workspace_mcp",
  "set_workspace_plugins",
  "team_config",
  "team_config_set",
  "usage",
  "workspace_branch",
  "workspace_diff",
  "workspace_scripts",
  "write_file",
] as const;

export type IpcCommand = (typeof IPC_COMMANDS)[number];

export function invoke<T>(
  command: IpcCommand,
  args?: InvokeArgs,
  options?: InvokeOptions,
): Promise<T> {
  return tauriInvoke<T>(command, args, options);
}
